### ISSUE TITLE
shouldn't crate::delay::Delay::poll call ctx.waker.wake?

### ISSUE THREAD

**Issue by zserik** [irrustible/async-oneshot#1]
e.g. I think the code for `async_oneshot::delay::Delay::poll` should look like the following instead, to avoid the potential scenario of a task which is never polled again because it's never waked again:
```rust
    fn poll(self: Pin<&mut Self>, ctx: &mut Context) -> Poll<()> {
        let mut this = Pin::into_inner(self);
        if this.done {
            Poll::Ready(())
        } else {
            this.done = true;
            ctx.waker().wake_by_ref(); // added line
            Poll::Pending
        }
    }
```
This change doesn't seem to incur any measurable additional performance cost.

```
/// benchmark results before change:
test create                ... bench:         100 ns/iter (+/- 6)
test create_send           ... bench:         132 ns/iter (+/- 6)
test create_send_recv      ... bench:         151 ns/iter (+/- 6)
test create_wait_send_recv ... bench:         549 ns/iter (+/- 31)

/// benchmark results after change:
test create                ... bench:         100 ns/iter (+/- 3)
test create_send           ... bench:         130 ns/iter (+/- 3)
test create_send_recv      ... bench:         151 ns/iter (+/- 4)
test create_wait_send_recv ... bench:         565 ns/iter (+/- 44)
```

**Comment by jjl** [comment]
Ordinarily, yes. But in this case, we're messing with the waker by hand, so it's *undesirable* to have this behaviour. we guarantee it will be woken again because the receiver will always wake the sender, even if it's just by dropping.

Does that make sense to you? Or am I missing something?

**Comment by jjl** [comment]
`Delay` no longer exists. It's been moved to [futures-micro](https://github.com/irrustible/futures-micro) as the `delay` function. I also replaced it with `poll_state` (also from futures-micro).
