### ISSUE TITLE
Preview/Feedback

### ISSUE THREAD

**Issue by jjl** [irrustible/async-oneshot#17]
Hi folks,

I've pushed most of a rewrite to the [async-hatch branch](https://github.com/irrustible/async-oneshot/tree/async-hatch) to give you some visibility into what the next release will entail.

First up, there have been significant changes to the user-visible API surface to accommodate new features. I recommend starting with the [new README](https://github.com/irrustible/async-oneshot/tree/async-hatch#readme). Nonetheless, I expect a lot of code will just continue to work because I've tried to preserve the familiar API for the default case.

Most significantly, senders and receivers may now send more than one message during their lifetime. If you don't need more than one message, you may also choose to close as part of the next operation, which will make the destructor cheaper.

Internally, everything has changed again. We do our own refcounting to cut out the Arc. We've cut back on the atomic flags and now take a lock more often.  We now have full no-allocator support and even support for manual memory management. We are now a one-stop shop for synchronising two tasks or threads.

I've also changed the license to the more permissive Apache2/LLVM exception, like futures-micro uses (which would enable use in the linux kernel). I don't believe any old code survived the refactor (except perhaps commented out as a guide to the remaining work i have to do). Nonetheless, if anyone has a problem with it, I'm open to alternatives...

Performance is now pretty amazing tbh:
* Create/destroy is down to around 30ns (from 50) 
* Everything else is sub-11ns.

There's still a bunch of important TODOs:

* Sender.wait
* Many more tests and benchmarks.
* Documentation  improvements
* Release new local version of `wookie` used in the test suite and benches (the old one tripped miri)

Now, as you might have guessed from the name of the branch (`async-hatch`), I'm intending a rename. Now that we can send multiple messages, `oneshot` doesn't seem like a good name anymore. If you can think of a better one that isn't already taken on crates, let's hear it.

Also let's hear any feedback you have in general. I expect to release async-hatch at 1.0.0, so let's get it ready before I do that!

**Comment by jjl** [comment]
Fixes #15 #16

**Comment by jjl** [comment]
@zseri you've contributed in the past

**Comment by jjl** [comment]
@cynecx you've contributed in the past

**Comment by jjl** [comment]
I've just pushed a bunch of updates. Mostly, `Sender.wait` is now implemented, tested and benchmarked. I've also released a new version of wookie for the dev-dependencies.

I've still only written the tests for box-backed hatches with async support. The rest need doing before we can call it releasable.

I would like to test a few more benchmark scenarios, but it's quite difficult to actually write isolated benchmarks. As we take everything by mut ref these days, we've been able to switch to criterion's `iter_batch_ref` which avoids billing us for the destructor, but i'd like to be able to benchmark receiver waiting without getting billed for it too, but there are more practical difficulties testing things. It might suffice to add box support to wookie, but it's being slightly unfair to penalise it with derefing some random box vs a stack var.

**Comment by cynecx** [comment]
I don't have much time reviewing all this, however it might be interesting to utilize https://github.com/tokio-rs/loom and run tests through loom, to catch potential concurrency bugs.

**Comment by jjl** [comment]
Perhaps surprisingly, I'm not actually worried about the correctness of the memory orderings (which is what loom is good for). I'm pretty sure they're correct because it's actually a very simple case (with the 'async' feature enabled anyway - everything takes a lock across the same atomic!)

Mostly I just wanted some feedback on the new api as a user.

**Comment by jjl** [comment]
Replaced with #18
