### ISSUE TITLE
Blocking receive

### ISSUE THREAD

**Issue by siriux** [irrustible/async-oneshot#19]
It would be nice to include a blocking version of receive like the one in the oneshot crate for interoperability with sync code:

https://docs.rs/oneshot/0.1.3/oneshot/struct.Receiver.html#method.recv

The async_channel crate also has this method:

https://docs.rs/async-channel/latest/async_channel/struct.Receiver.html#method.recv

**Comment by jjl** [comment]
i've previously experimented with including one, but i didn't think the api surface was worth it when you can just use `block_on` from futures_lite (which you probably already depend on) or some other small executor. at a high level, the futures 'Waker'  model seems to be approximately the right one to represent waiting either asynchronously or synchronously, so it makes more sense to me to just use that model.

**Comment by siriux** [comment]
Thanks for your answer
