### ISSUE TITLE
Redundant ManuallyDrop

### ISSUE THREAD

**Issue by cynecx** [irrustible/async-oneshot#3]
https://github.com/irrustible/async-oneshot/blob/aa2459625cfd5b0689c55aa0d8142d8207e0ce0d/src/inner.rs#L11

`ManuallyDrop<MaybeUninit<T>>` is redundant as `MaybeUninit` will never call the drop impl.

**Comment by jjl** [comment]
I tried to apply this change and then got lost trying to figure out how to rewrite `take_value`. Happy to accept a PR if you can figure it out :)

**Comment by cynecx** [comment]
Isn't `val.as_ptr().read()` the same thing?

**Comment by jjl** [comment]
Ah yes, that works. Thanks!
