### ISSUE TITLE
Segfault while dropping Receiver

### ISSUE THREAD

**Issue by boardwalk** [irrustible/async-oneshot#5]
I'm seeing a segfault. It seems to occur when the sender is alive, the receiver is being awaited, and a container of the futures is destructed -- while at least doing something to make sure the futures are polled.

This the most minimal reproducer I've been able to find: https://github.com/boardwalk/oneshot_crash/blob/master/src/main.rs

**Comment by jjl** [comment]
*sigh* guess i'd better recheck all the invariants by hand.

**Comment by jjl** [comment]
Actually it was incredibly mundane - i was waking the receiver instead of the sender during receiver drop. Fixed in 0.3.2. Thanks for the detailed report!
